homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 161
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  base_url: ha.lan:80

# Checks for available updates
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

media_player:
  - platform: cast
    name: chromecast-lr
    host: chromecast-lr.lan
  - platform: cast
    name: home-mini-lr
    host: home-mini-lr.lan
  - platform: roku
    name: roku-tv
    host: roku-tv.lan

climate: 
  platform: radiotherm
  host: thermostat.lan

sensor: !include_dir_merge_list sensor
automation: !include_dir_merge_list automation
script: !include_dir_named scripts
shell_command: !include_dir_named shell_command
group: !include groups.yaml