- platform: wunderground
  api_key: !secret wundergroud_api
  monitored_conditions:
    - alerts
    - weather
    - location
    - observation_time
    - temp_f
    - feelslike_f
    - wind_mph
    - wind_gust_mph
    - weather_1d
    - weather_1n
    - weather_2d
    - weather_2n
#    - weather_3d
#    - weather_3n
#    - weather_4d
#    - weather_4n
